print("คำนวณหาพื้นที่ 4 เหลี่ยมจตุรัส")
side = float(input("ใส่ความยาวด้าน: "))
print("= พื้นที่ของ 4 เหลี่ยมจตุรัสนี้ คือ "+str(side*2))
print("\n")
print("คำนวณหาพื้นที่ 4 เหลี่ยมผืนผ้า")
wide = float(input("ใส่ความกว้าง: "))
long = float(input("ใส่ความยาว: "))
print("= พื้นที่ของ 4 เหลี่ยมผืนผ้า คือ "+str(long*wide))
print("\n")
print("คำนวณหาพื้นที่วงกลม")
radius = float(input("ใส่รัสมี: "))
pi = 3.14
print("= พื้นที่ของวงกลม คือ "+str(pi*radius**2))
