print("โปรดกรอกข้อมูลต่อไปนี้")
name = str(input("ชื่อ : "))
age = int(input("อายุ : "))
studentcode = int(input("รหัสประจำตัวนักเรียน : "))
year = int(input("ระดับชั้นปี : "))
nickname = str(input("ชื่อเล่น : "))
tall = float(input("ส่วนสูง : "))
weight = float(input("น้ำหนัก : "))
print(f"ชื่อ:"+{name}+" อายุ:"+{age})
print(f"รหัสประจำตัวนักเรียน:"+{studentcode}+" ระดับชั้นป:"+{year})
print(f"ชื่อเล่น:"+nickname)
print(f"ส่วนสูง:"+{tall}+" น้ำหนัก: "+{weight})
plus = tall + weight
print(f"ส่วนสูง"+" + "+"น้ำหนัก"+" ="+{plus})