print("โปรดกรอกข้อมูลต่อไปนี้")
name = str(input("ชื่อ : "))
age = int(input("อายุ : "))
studentcode = int(input("รหัสประจำตัวนักเรียน : "))
year = int(input("ระดับชั้นปี : "))
nickname = str(input("ชื่อเล่น : "))
tall = float(input("ส่วนสูง : "))
weight = float(input("น้ำหนัก : "))
print("ชื่อ:"+name+" อายุ:"+(str(age)))
print("รหัสประจำตัวนักเรียน:"+(str(studentcode))+" ระดับชั้นป:"+(str(year)))
print("ชื่อเล่น:"+nickname)
print("ส่วนสูง:"+(str(tall))+" น้ำหนัก: "+(str(weight)))
plus = tall + weight
print("ส่วนสูง"+" + "+"น้ำหนัก"+" ="+(str(plus)))